### ISSUE TITLE
Full git file

### ISSUE THREAD

**Issue by pouretrebelle** [pouretrebelle/chareads.com#88]
The git repo is maxed out (100gb?) because of the daily image regeneration in `gh-pages`. I stopped regenerating them in #87 so this shouldn't be a problem going forward, but need to nuke all the history of the `gh-pages` branch to get the git file size down.

https://stackoverflow.com/questions/34657031/how-do-you-remove-a-branch-and-all-of-its-history-locally-and-remotely

https://github.com/pouretrebelle/chareads.com/commit/97ad080710637017e4584449c00ab1171aaa44d5 initial commit to branch

```[tasklist]
### Tasks
- [x] Delete all of the gh-pages branch history
- [x] Deploy a fresh copy
- [x] FIx nightly deplo
- [ ] Make future deploys delete the previous commit
```

**Comment by pouretrebelle** [comment]
I considered making every deploy fixup the last commit so it doesn't bloat, but if it's just a daily update of the youtube stats, the only files it effects is the page data https://github.com/pouretrebelle/chareads.com/commit/5ed0c9f436dfef615cb76b5dfdd3e5ceeecab5fa 

This is still quite bulky so in https://github.com/pouretrebelle/chareads.com/commit/b78b6c72ab50abcd14998a893a7937c5c088b3f2 I prettified the page data so it's just small line changes.
